FROM node:22-bookworm-slim

WORKDIR /app
COPY package*.json ./
COPY app_common ./app_common
COPY app_batch ./app_batch

# 依存関係インストール&ビルド
RUN npm ci

# ヘルスチェック（オプション）
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD node -e "console.log('Batch service is running')" || exit 1

# shacme.prismaを基にDBテーブルを作成 $$ バッチアプリケーション起動
WORKDIR /app/app_batch
CMD npx prisma db push --schema=../app_common/prisma/schema.prisma && npm run dev