FROM node:22-bookworm-slim

WORKDIR /app
COPY package*.json ./
COPY app_common ./app_common
COPY app_web ./app_web

# 依存関係インストール&ビルド
RUN npm ci

# 作業ディレクトリ作成と権限付与。アプリの実行はnodeユーザーで行うため、権限を許可しないとアプリ実行中に権限拒否される
RUN mkdir -p /app/.next/cache/images \
    && chown -R node:node /app/.next

# ヘルスチェック
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD wget -qO- http://localhost:3000/health || exit 1

# Webアプリケーション起動
WORKDIR /app/app_web
CMD ["npm", "run", "dev"]