services:
# DBサーバー
  db:
    image: postgres:14
    container_name: db_postgres
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-store:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # Redis キャッシュサーバー
  cache:
    image: redis:8-alpine
    container_name: app_cache
    ports:
      - "6379:6379"
    volumes:
      - ../app_cache/redis.conf:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf
    restart: no
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # バッチアプリケーション
  batch:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.batch
    container_name: app_batch
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      BATCH_SCHEDULE: ${BATCH_SCHEDULE:-development}
      CACHE_HOST: cache
      CACHE_PORT: 6379
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      cache:
        condition: service_started
      db:
        condition: service_healthy
    restart: no
    volumes:
      # ホスト側をマウントして、コードの反映を「docker-compose up」(コンテナ再起動)で可能にする。無いと「docker-compose up --build」（コンテナを再作成）する必要がある。
      - ../:/app
      # ホスト側とコンテナ側が干渉しないようにコンテナ内で生成するものを保護する。
      - /app/node_modules
      - /app/app_common/node_modules
      - /app/app_common/dist
      - /app/app_batch/node_modules
    command: >
      sh -c "npx turbo run build --filter=app_common --force &&
             npx prisma db push --schema=./app_common/prisma/schema.prisma && 
             npm run dev --workspace=app_batch"

  # Webアプリケーション
  web:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.web
    container_name: app_web
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      CACHE_HOST: cache
      CACHE_PORT: 6379
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - cache
      - db
    restart: no
    volumes:
      # ホスト側をマウントして、ホットリロードを可能にする。app_webに関してはコード反映はコンテナ再起動も不要
      - ../:/app
      - /app/node_modules
      - /app/app_common/node_modules
      - /app/app_common/dist
      - /app/app_web/node_modules
      - /app/app_web/.next
    command: >
      sh -c "npx turbo run build --filter=app_common --force &&
             npm run dev --workspace=app_web"

volumes:
  db-store: