%%{init: {'theme': 'dark', 'themeVariables': { 'lineColor': '#ffffffff' }}}%%
sequenceDiagram
    participant B as Batch Server
    participant R as Redis
    participant D as PostgreSQL
    participant E as 外部サイト

    B->>B: 商品キャッシュを削除 (Repository)
    loop 定期実行
        Note over B: Application Service
        B->>E: サイト接続 (Scraper)
        E-->>B: HTMLを返却 (Scraper)
        B->>B: HTMLから商品データ抽出 (Scraper)
        B->>D: 商品データ永続化 (Repository)
        B->>R: 商品データを商品キャッシュにマージ (Repository)
    end